version: "3.7"

services:
  backend:
    image: aryarajalves/interface-gerencia-produtos-banco:backend-1.0.0
    build: 
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        # Regra 2: Acesso via path /api no domínio principal (Same-Origin)
        - traefik.http.routers.rag-backend-path.rule=Host(`produtos.aryaraj.shop`) && PathPrefix(`/api`)
        - traefik.http.routers.rag-backend-path.entrypoints=websecure
        - traefik.http.routers.rag-backend-path.tls.certresolver=letsencryptresolver
        - traefik.http.routers.rag-backend-path.middlewares=backend-stripprefix
        
        # Middleware para remover o /api da URL antes de enviar pro backend
        - traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api
        
        - traefik.http.services.rag-backend.loadbalancer.server.port=8000
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - RATE_LIMIT_READ=10/minute
      - RATE_LIMIT_WRITE=5/minute
    networks:
      - network_swarm_public

  frontend:
    image: aryarajalves/interface-gerencia-produtos-banco:frontend-1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.rag-frontend.rule=Host(`produtos.aryaraj.shop`)
        - traefik.http.routers.rag-frontend.entrypoints=websecure
        - traefik.http.routers.rag-frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.rag-frontend.loadbalancer.server.port=80
    networks:
      - network_swarm_public

networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
