version: "3.7"

services:
  backend:
    image: aryarajalves/interface-gerencia-produtos-banco:backend-latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.rag-backend.rule=Host(`api.produtos.agency10x.com.br`)
        - traefik.http.routers.rag-backend.entrypoints=websecure
        - traefik.http.routers.rag-backend.tls.certresolver=letsencryptresolver
        - traefik.http.services.rag-backend.loadbalancer.server.port=8000
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - RATE_LIMIT_READ=${RATE_LIMIT_READ:-10/minute}
      - RATE_LIMIT_WRITE=${RATE_LIMIT_WRITE:-5/minute}
    networks:
      - network_swarm_public

  frontend:
    image: aryarajalves/interface-gerencia-produtos-banco:frontend-latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.rag-frontend.rule=Host(`produtos.agency10x.com.br`)
        - traefik.http.routers.rag-frontend.entrypoints=websecure
        - traefik.http.routers.rag-frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.rag-frontend.loadbalancer.server.port=80
    networks:
      - network_swarm_public

networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
